name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        uses: ./.github/actions/install-linux-deps

      - name: Install cargo-codspeed
        run: cargo install cargo-codspeed --locked

      - name: Build Benchmarks
        run: cargo codspeed build -p benches

      - name: Run Benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: cargo codspeed run -p benches
          token: ${{ secrets.CODSPEED_TOKEN }}
